### ISSUE TITLE
Fill the gaps in the grid?

### ISSUE THREAD

**Issue by PhantomFFR** [Vulpelo/hide-youtube-shorts#10]
Hello,

The letsblockit-ublock-script that blocked shorts (and stopped working yesterday) did not just hide the shorts in the grid-like overview, but also made it appear as if there were no shorts blocked (it moved non-shorts into the spots of blocked shorts). Thus the grid view had no random gaps/always showed the maximum of 6 real videos per row.

Would it be possible for this extension to do the same?

**Comment by Vulpelo** [comment]
Hi,

Where do those gaps appear? Are you talking about gaps after removing shorts on the home page or subscription/search page?

Because I am not sure if shorts still appear in place of normal video elements on home page, but instead they are appearing in dedicated shelf. (or at least they no longer appear for me. I tried watching few shorts hoping that would make them appear but to no avail)

If you are talking about subscription page there videos are rearranging automatically after hiding shorts with no need for extra code.

**Comment by PhantomFFR** [comment]
Hey, thanks for the reply. I hope it's ok to link to the [github discussion ](https://github.com/letsblockit/letsblockit/issues/385#issuecomment-1496309728)on the letsblockit-script, where I posted screenshots of the rearrengement-issue.

**Comment by Vulpelo** [comment]
Hi, I have added option to rearrange videos during process of hiding shorts. Currently changes are sitting on "fill-the-gaps-in-the-grid" branch. 
I have tested it on the Home page grid but since I am not yet able to properly test it on new version of subscription page (youtube hasn't yet pushed new changes to my region) I wont be pushing those changes to a new package.  
Fell free to test if those changes are working correctly for you, thanks.

**Comment by Bhaalspawn** [comment]
Hello, i still have gaps in subscriptions (maybe also in other sections but this is the most important). i can't see this "rearrange videos" option

![Immagine 2023-05-13 165627](https://github.com/Vulpelo/hide-youtube-shorts/assets/20135076/20892e2b-1c74-467c-8569-3276b1a91d3e)

**Comment by Vulpelo** [comment]
I have added an experimental option for rearranging videos on the grid (I still have old subscription page, so I was somewhat testing rearrangement on the home page instead). 
I have pushed the new version (1.3.0) to plugin store.

**Comment by Bhaalspawn** [comment]
> I have added an experimental option for rearranging videos on the grid (I still have old subscription page, so I was somewhat testing rearrangement on the home page instead).
> I have pushed the new version (1.3.0) to plugin store.

Thanks, it seems it's working, at least for the video i have now in the subscriptions page

**Comment by Vulpelo** [comment]
As in #15 issue, I uploaded 1.3.1 version to plugin store, that should fix having excessive videos in single row on new subscription page.
