### ISSUE TITLE
Option to not hide from youtuber pages?

### ISSUE THREAD

**Issue by bakudaz** [Vulpelo/hide-youtube-shorts#19]
I'd like an option for shorts to be viewable when looking at a YouTuber's page, specifically their Shorts Tab.

I want to hide shorts from my main subscription feed because it's already too cluttered, and I could very easily just check their shorts tab if I'm in the mood. Too many places are doing Shorts for my tastes, but I know some channels that are really good with them.

I'd like an option to see them on search results too.

**Comment by Vulpelo** [comment]
Thank you for suggesting new feature.

Videos in channel's shorts tab, when I have checked some time ago weren't disappearing. So I guess youtube has enrolled a new update. 

I have added changes for shorts to not dissappear when under channel's shorts tab (since there is no reason to delete then when they are listed in seperate tab) and I have added options to hide shorts only on some pages (home/subscription/search/channel's home page) 

The new version (v1.5.0) was published to plugin store.
