### ISSUE TITLE
Close button for a shelf with shorts on subscription page

### ISSUE THREAD

**Issue by skyfox1977** [Vulpelo/hide-youtube-shorts#24]
Instead of just blocking shorts on subscriptions, I want to be able to have a close button of shorts and maybe a timer on how long it will be closed after using the button.

**Comment by Vulpelo** [comment]
From what I understood you want a toggle button directly on Subcription page (eg. next to buttons for layout change in top-right) which will enable/disable hiding shorts? [essencially the same toggle button that is currently in addon's menu "hiding on subscription page", but visible on subscription page]
Additionally with option to automatically disable hiding shorts on subscription page after X minutes.


Currently on subscription page I am not actually hiding shorts but I am deleting them, so reshowing shorts wont be possible without reloading the page. 
In previous versions of the addon I was hiding shorts, but unfortunatelly youtube has made some changes to the grid system on Subscription page, which caoused showing uneven amount of videos per row when hiding shorts (more or less than should be). The fix for this was simply deleting shorts instead.

Few days ago YT again has modified subscription page and shorts are now located on seperate dedicated row (like on home page), which also means I wont be able to test a new changes related to hiding instead of deleting shorts. 

But as far as it goes for just adding a button on the subscription page which will work as existing button in addon's menu, then I can look into it.

**Comment by skyfox1977** [comment]
Maybe I was a bit unclear on what I meant. I was thinking about a close button to delete (or hide) beside the "View all" on subscription page. Like they already have on the "Home" page. No need for a toggle or a timer. A refresh on the page works totally fine for me, as long as I can close the "Shorts" on the subscription page :)

**Comment by Vulpelo** [comment]
I see, you are referring to the shelf with shorts that has recently been added to the subscription page (recently for me, but I know some user groups get new YT features sooner or even months later).

I can look into adding a close button to that shelf, like YT has done it for the shelf on the home page.

**Comment by skyfox1977** [comment]
Yes, that shelf, It was added for me 2 days ago, this is why I installed your superb extension in the first place, while I sometimes want to watch shorts I dont want it completely removed from the subscription, so I think it needs a close button instead.
Thank you :)

**Comment by Vulpelo** [comment]
Update with the close button feature (v1.5.3) was pushed to the plugin store, and should be live soon

**Comment by skyfox1977** [comment]
> 

Thank you :)
