### ISSUE TITLE
Not available on the Chrome store anymore

### ISSUE THREAD

**Issue by WeebNetsu** [Vulpelo/hide-youtube-shorts#26]
Maybe just update the readme to say they removed it from their store?

**Comment by Vulpelo** [comment]
Thanks for the information. 
I have sent an email to the Google team regarding that, hopefully the plugin will be available again on the chrome web store soon.

I have also updated Readme file.

**Comment by Vulpelo** [comment]
Plugin Is again available on chrome store, but due to trademark violation, now item is under different name. Also due to an unknown wait till reinstating plugin on the store, I have republished it under a different link address.

I have updated the Readme.md file with the new link to the plugin on the chrome store.
