### ISSUE TITLE
Add option to hide "short" videos too

### ISSUE THREAD

**Issue by mrx23dot** [Vulpelo/hide-youtube-shorts#36]
There are videos which are short like 28seconds, but not marked as shorts.

e.g. https://www.youtube.com/@hunteradams9430/videos

ideally there could be an option with minimum length to show, e.g. 60seconds

**Comment by Vulpelo** [comment]
Hi, thanks for suggesting the feature. I have pushed the feature in the next version (v1.7.0) and is shown in experimental section.

Unfortunatelly depending on the version of youtube's website that google currently has pushed in your region, this feature might not work as intended when revisiting the same youtube page (e.g. subscription page) without fully reloading the website (pressing reload the page button in the browser). 
Just like for me, the feature didn't work correctly untill recently (youtube probably has pushed some another update)

**Comment by Vulpelo** [comment]
I imagine there are some additional metadata files generated and added to the plugin by Mozilla when the plugin gets published into the store. 

For now, until the plugin gets reviewed by mozilla and uploaded into the store, you can install this plugin temporarily like described in Readme instructions.

**Comment by Vulpelo** [comment]
I missed that you wanted specifically to hide videos on channel's 'videos' subpage. Currently plugin allows hiding videos on channel's 'home' subpage and not hide on 'videos' subpage (that is because in 'videos' subpage there are no shorts).

More specifically  line 21 in main.js file:
```channelPage: { active: true, reg: /@[^\/]*(\/featured)?$/, nodeSelector: "ytd-browse[page-subtype='channels']", node: null},```
filters only channel's 'home' subpage.

After changing it to:
```channelPage: { active: true, reg: /@[^\/].*$/, nodeSelector: "ytd-browse[page-subtype='channels']", node: null},```
Will hide videos on all channel's subpages

I will look at it and add appropriate change later when I get a chance.

**Comment by Vulpelo** [comment]
I have merged new changes. Now it should hide short videos anywhere including on channel's videos subpage.

You can test changes by downloading a zip file from master branch and following descritpion in readme file. I will make a release and I will publish it to plugin store tomorrow.
