### ISSUE TITLE
A shortcut would be nice.

### ISSUE THREAD

**Issue by audiogamer22** [Vulpelo/hide-youtube-shorts#42]
I'm blind and a shortcut to toggle this addon on and off would be awesome!

I don't think it's on by default is it? I still see the shorts tab, I honestly forgot I had the addon and pressed enter on not interested when the shorts heading came up this week.

**Comment by Vulpelo** [comment]
Hello,
Hiding shorts videos is on by default but the main shorts tab (next to home and subscriptions tabs) is not hidden by default. Also there is other shorts tab that is on channels page (shows up whenever channel has published some shorts) is also not getting hidden and currently plugin has no option to hide it.

You mentioned "the shorts heading came up this week", so I guess the problem came up recently. So it is possible YouTube is rolling out a new update to the website for some users which potentially could break plugin's hiding shorts capability. 

Regarding hiding shorts tab I could change the default settings so it is on by default.
As for shortcut, I could add it by default under 'H' key which would toggle hiding shorts (shorts videos, main shorts tab, notification for shorts in notification menu). It would work like existing YouTube shortcuts like 'M' key is for mute or 'K' is for play/pause.

**Comment by audiogamer22** [comment]
I've realised that for me it's just pressing a button and the shorts go away for 30 days so honestly, I don't need this addon.

I'll close the ticket, thanks for responding.
